# TODO
# crowd password (line: 47)
# Global Env 설정 (line 50)
# Credential 설정 (line: 114)
jenkins:
  controller:
    # image: 992382711213.dkr.ecr.ap-northeast-2.amazonaws.com/aicc-shr-ecr-jenkins
    # tag: latest
    image:
      # -- Controller image registry
      registry: "docker.io"
      # -- Controller image repository
      repository: "jenkins/jenkins"
      tag: jdk21
    pullPolicy: "Always"
    release: 1
    runAsUser: 0
    jenkinsUriPrefix: "/jenkins"
    jenkinsOpts: "--requestHeaderSize=258140"
    javaOpts: >
      -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul
      -Duser.timezone=Asia/Seoul
      -Dhudson.model.WorkspaceCleanupThread.disabled=true
    installPlugins: false
    probes:
      startupProbe:
        periodSeconds: 30
    overrideArgs:
      - --httpPort=7080
    servicePort: 7080
    targetPort: 7080
    resources:
      requests:
        cpu: "250m"
        memory: "400Mi"
      limits:
        cpu: "250m"
        memory: "400Mi"
    JCasC:
      securityRealm: |-
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
            - id: "rudgh21"
              name: "Jenkins Admin"
              password: "password"
            - id: "nlee"
              name: "Jenkins Admin(nlee)"
              password: "password"
            - id: "hjkim"
              name: "Jenkins Admin(hjkim)"
              password: "password"
      # configScripts:
      #   general-settings: |
      #     jenkins:
      #       systemMessage: Welcome to KYHLEE's CI/CD.
      #       authorizationStrategy:
      #         projectMatrix:
      #           permissions:
      #           - "GROUP:Overall/Read:authenticated"
      #       globalNodeProperties:
      #       - envVars:
      #           env:
      #           - key: "ARGO_GIT_URL"
      #             value: "https://rudgh21.com"
                
      #   crendentials-config: [] 
      #   plugin-settings: []
    jenkinsAdminEmail: ygrhu0325@naver.com
    ingress:
      enabled: true
      ingressClassName: traefik
      hostName: rudgh21.com
      paths:
        - path: /jenkins
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 7080
      annotations: 
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
                
  rbac:
    create: true
  serviceAccount:
    create: true

  serviceAccountAgent:
    create: true
    name: jenkinsrudgh21-worker

  agent:
    websocket: true
    namespace: jenkins
    podName: jenkins_worker
    customJenkinsLabels: jenkins_worker
    image:
      repository: "jenkins_worker"
      tag: "latest"

    # timeout설정을 2배로 설정
    kubernetesConnectTimeout: 10
    kubernetesReadTimeout: 30
    containerCap: ""
    connectTimeout: 300
    jenkinsUrl: http://rudgh21.com/jenkins
    command:

    resources:
      requests:
        cpu: 250m
        memory: 400Mi
      limits:
        cpu: 500m
        memory: 800Mi
    workingDir: /data/jenkins_worker
    args: ""
    volumes:
      - type: PVC
        claimName: kyhlee-jenkins-worker-pvc
        mountPath: /data/jenkins_worker
        readOnly:
          false

    additionalContainers:
      - sideContainerName: kaniko
        image: 
          repository: "kaniko"
          tag: latest
        command: "/busybox/cat"
        args: ""
        workingDir: "/data/jenkins_worker"
        alwaysPullImage: true
        TTYEnabled: true
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

  persistence:
    enabled: true
    existingClaim: kyhlee-jenkins-pvc
    mountPath: /var/jenkins_home
