apiVersion: v1
kind: PersistentVolume
metadata:
  name: kyhlee-jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/rudgh21/Downloads/jenkins-ecs" # 로컬 서버의 실제 경로
    type: DirectoryOrCreate
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: kyhlee-jenkins
    namespace: jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyhlee-jenkins
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi